name: Test Project
on: push  # Trigger when code is pushed
jobs:
  test:   # Job name
    runs-on: ubuntu-latest
    steps:
      - name: Download the code to the repo
        uses: actions/checkout@v4
      - name: Install Node js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing dependencies
        run: npm ci
      - name: Testing
        run: npm test
  deploy:
    needs: test # deploy will run only after test job is sucesful
    runs-on: ubuntu-latest
    steps:
      - name: Get-code
        uses: actions/checkout@v4
      - name: download NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependecies 
        run: npm ci
      - name: build project
        run: npm run build
      - name: Deploy
        run: echo "Deply......."        


         
    
